version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=thado_robot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password_here
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=False
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=thado_robot
      - DB_USER=postgres
      - DB_PASSWORD=your_password_here
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --config gunicorn.conf.py core.wsgi:application"

volumes:
  postgres_data:
  static_volume:
  media_volume:
