# Generated by Django 4.2.7 on 2025-09-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Giới thiệu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('it', 'Công nghệ thông tin'), ('hr', 'Nhân sự'), ('finance', 'Tài chính'), ('marketing', 'Marketing'), ('sales', 'Kinh doanh'), ('support', 'Hỗ trợ khách hàng'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Phòng ban'),
        ),
    ]
