# Generated by Django 4.2.7 on 2025-09-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_address_remove_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('staff', 'Nhân viên')], default='staff', max_length=20, verbose_name='Vai trò'),
        ),
    ]
