# Generated by Django 4.2.7 on 2025-09-17 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Tên đăng nhập này đã tồn tại.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username không được chứa các ký tự: < > " \' ; & ( )', regex='^[^<>"\\\';&()]+$')], verbose_name='Tên đăng nhập'),
        ),
    ]
